# Importing Libraries

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA

In [3]:
dataset1=pd.read_csv("Cleaned_Data.csv")
dataset1.head()

Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Female  Gender_Male  Gender_Transgender  Severity_Mild  \
0              0            1                   0              1   
1              0            1                   0              1   
2              0            1                   0              1   
3              0            1                   0              0   
4              0            1                   0              0   

   Severity_Moderate  Severity_None  Severity_Severe  Contact_Dont-Know  \
0                  0              0                0                  0   
1                  0              0                0                  0   
2                  0              0                0                  1   
3                  1              0                0                  0   
4                  1              0                0                  0   

   Contact_No  Contact_Yes  
0           0            1  
1           1            0  
2           0            0  
3           0            1  
4           1            0  

[5 rows x 26 columns]

In [4]:
dataset1.shape

(316800, 26)

In [5]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316800 entries, 0 to 316799
Data columns (total 26 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Fever                    316800 non-null  int64
 1   Tiredness                316800 non-null  int64
 2   Dry-Cough                316800 non-null  int64
 3   Difficulty-in-Breathing  316800 non-null  int64
 4   Sore-Throat              316800 non-null  int64
 5   None_Sympton             316800 non-null  int64
 6   Pains                    316800 non-null  int64
 7   Nasal-Congestion         316800 non-null  int64
 8   Runny-Nose               316800 non-null  int64
 9   Diarrhea                 316800 non-null  int64
 10  None_Experiencing        316800 non-null  int64
 11  Age_0-9                  316800 non-null  int64
 12  Age_10-19                316800 non-null  int64
 13  Age_20-24                316800 non-null  int64
 14  Age_25-59                316800 non-

In [6]:
dataset1.isnull().sum()

Fever                      0
Tiredness                  0
Dry-Cough                  0
Difficulty-in-Breathing    0
Sore-Throat                0
None_Sympton               0
Pains                      0
Nasal-Congestion           0
Runny-Nose                 0
Diarrhea                   0
None_Experiencing          0
Age_0-9                    0
Age_10-19                  0
Age_20-24                  0
Age_25-59                  0
Age_60+                    0
Gender_Female              0
Gender_Male                0
Gender_Transgender         0
Severity_Mild              0
Severity_Moderate          0
Severity_None              0
Severity_Severe            0
Contact_Dont-Know          0
Contact_No                 0
Contact_Yes                0
dtype: int64

In [7]:
smote=SMOTE()
balanced_msx,balanced_msy=smote.fit_resample(dataset1.iloc[:,0:19],dataset1.iloc[:,19])
print(balanced_msx.shape)
print(balanced_msy.shape)

(475200, 19)
(475200,)


In [17]:
scaler=StandardScaler()
scale_x=scaler.fit_transform(balanced_msx)
scale_x

array([[ 1.48328328,  1.00037465,  0.88120843, ..., -0.70581817,
         1.41381189, -0.70819518],
       [ 1.48328328,  1.00037465,  0.88120843, ..., -0.70581817,
         1.41381189, -0.70819518],
       [ 1.48328328,  1.00037465,  0.88120843, ..., -0.70581817,
         1.41381189, -0.70819518],
       ...,
       [-0.67418005, -0.99962549, -1.13480531, ..., -0.70581817,
         1.41381189, -0.70819518],
       [ 1.48328328,  1.00037465,  0.88120843, ..., -0.70581817,
        -0.70730767,  1.41204012],
       [-0.67418005, -0.99962549, -1.13480531, ..., -0.70581817,
         1.41381189, -0.70819518]])

In [8]:
severity_mild=dataset1.iloc[:,19]
severity_moderate=dataset1.iloc[:,20]
severity_none=dataset1.iloc[:,21]
severity_severe=dataset1.iloc[:,22]

In [9]:
print(severity_mild.value_counts())
print(severity_none.value_counts())
print(severity_moderate.value_counts())
print(severity_severe.value_counts())

0    237600
1     79200
Name: Severity_Mild, dtype: int64
0    237600
1     79200
Name: Severity_None, dtype: int64
0    237600
1     79200
Name: Severity_Moderate, dtype: int64
0    237600
1     79200
Name: Severity_Severe, dtype: int64


In [10]:
real_x=dataset1.iloc[:,0:19]
print(real_x.shape)

(316800, 19)


# For Mild Severity

## Training Models

In [18]:
train_x,test_x,train_y,test_y=train_test_split(scale_x,balanced_msy,test_size=0.30,random_state=123)
print(train_x.shape)
print(train_y.shape)
print(test_x.shape)
print(test_y.shape)

(332640, 19)
(332640,)
(142560, 19)
(142560,)


In [19]:
lr=LogisticRegression()
lr.fit(train_x,train_y)
pred_lr=lr.predict(test_x)
print("The confussion metrix for Logistic Regression is:\n",metrics.confusion_matrix(test_y,pred_lr))
print("The accuracy of Logistic Regression is:\t\t",metrics.accuracy_score(test_y,pred_lr))
print("The recal score of Logistic Regression is is:\t\t",metrics.recall_score(test_y,pred_lr))
print("The precision of Logistic Regression is:\t\t",metrics.precision_score(test_y,pred_lr))
print("The f1 score of Logistic Regression is:\t\t",metrics.f1_score(test_y,pred_lr))

The confussion metrix for Logistic Regression is:
 [[31248 40152]
 [31312 39848]]
The accuracy of Logistic Regression is:		 0.49870931537598207
The recal score of Logistic Regression is is:		 0.5599775154581226
The precision of Logistic Regression is:		 0.4981
The f1 score of Logistic Regression is:		 0.5272294257740143


In [20]:
rf=RandomForestClassifier()
rf.fit(train_x,train_y)
pred=rf.predict(test_x)
print("The confussion metrix for Random forest is:\n",metrics.confusion_matrix(test_y,pred))
print("The accuracy of Random Forest Classifier is:\t\t",metrics.accuracy_score(test_y,pred))
print("The recal score of Random Forest Classifier is:\t\t",metrics.recall_score(test_y,pred))
print("The precision of Random Forest Classifier is:\t\t",metrics.precision_score(test_y,pred))
print("The f1 score of Random Forest Classifier is:\t\t",metrics.f1_score(test_y,pred))

The confussion metrix for Random forest is:
 [[33438 37962]
 [36495 34665]]
The accuracy of Random Forest Classifier is:		 0.47771464646464645
The recal score of Random Forest Classifier is:		 0.48714165261382797
The precision of Random Forest Classifier is:		 0.4773018298979718
The f1 score of Random Forest Classifier is:		 0.4821715454109203


In [21]:
ada=AdaBoostClassifier()
ada.fit(train_x,train_y)
pred_ada=ada.predict(test_x)
print("The confussion metrix for AdaBoost is:\n",metrics.confusion_matrix(test_y,pred_ada))
print("The accuracy of AdaBoost Classifier is:\t\t",metrics.accuracy_score(test_y,pred_ada))
print("The recal score of AdaBoost Classifier is is:\t\t",metrics.recall_score(test_y,pred_ada))
print("The precision of AdaBoost Classifier is:\t\t",metrics.precision_score(test_y,pred_ada))
print("The f1 score of AdaBoost Classifier is:\t\t",metrics.f1_score(test_y,pred_ada))

The confussion metrix for AdaBoost is:
 [[31303 40097]
 [31356 39804]]
The accuracy of AdaBoost Classifier is:		 0.4987864758698092
The recal score of AdaBoost Classifier is is:		 0.5593591905564924
The precision of AdaBoost Classifier is:		 0.49816648102026256
The f1 score of AdaBoost Classifier is:		 0.5269924070408643
